version: '3.8'

services:
  nginx:
    image: nginx:1.30
    container_name: nginx
    ports:
      - "8080:80"
      - "9999:9999"
    volumes:
      # - ${NGINX_CONF_PATH:-./nginx/nginx.conf}:/etc/nginx/nginx.conf:ro
      - ${NGINX_CONF_PATH}:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
      # as per "Serving Static Content" -- https://nginx.org/en/docs/beginners_guide.html#static
      - ./nginx/html:/data/www:ro
      - ./nginx/data/images:/data/images:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

  service-a:
    build:
      context: ./go_nginx
      dockerfile: Dockerfile
    container_name: service-a
    command: ["./service", "3001"]
    restart: unless-stopped

  service-b:
    build:
      context: ./go_nginx
      dockerfile: Dockerfile
    container_name: service-b
    command: ["./service", "3002"]
    restart: unless-stopped
