""" Simple WHOIS socket TCP client

@author: Federico Bau
"""
from pprint import pprint
import socket

WHOIS_SERVERS = {
    "ac" : "whois.nic.ac",
    "ae" : "whois.nic.ae",
    "aero":"whois.aero",
    "af" : "whois.nic.af",
    "ag" : "whois.nic.ag",
    "ai" : "whois.ai",
    "al" : "whois.ripe.net",
    "am" : "whois.amnic.net",
    "arpa" : "whois.iana.org",
    "as" : "whois.nic.as",
    "asia" : "whois.nic.asia",
    "at" : "whois.nic.at",
    "au" : "whois.aunic.net",
    "ax" : "whois.ax",
    "az" : "whois.ripe.net",
    "be" : "whois.dns.be",
    "bg" : "whois.register.bg",
    "bi" : "whois.nic.bi",
    "biz" : "whois.biz",
    "bj" : "whois.nic.bj",
    "bn" : "whois.bn",
    "bo" : "whois.nic.bo",
    "br" : "whois.registro.br",
    "bt" : "whois.netnames.net",
    "by" : "whois.cctld.by",
    "bz" : "whois.belizenic.bz",
    "ca" : "whois.cira.ca",
    "cat" : "whois.cat",
    "cc" : "whois.nic.cc",
    "cd" : "whois.nic.cd",
    "ch" : "whois.nic.ch",
    "ci" : "whois.nic.ci",
    "ck" : "whois.nic.ck",
    "cl" : "whois.nic.cl",
    "cn" : "whois.cnnic.net.cn",
    "co" : "whois.nic.co",
    "com" : "whois.verisign-grs.com",
    "coop" : "whois.nic.coop",
    "cx" : "whois.nic.cx",
    "cz" : "whois.nic.cz",
    "de" : "whois.denic.de",
    "dk" : "whois.dk-hostmaster.dk",
    "dm" : "whois.nic.dm",
    "dz" : "whois.nic.dz",
    "ec" : "whois.nic.ec",
    "edu" : "whois.educause.edu",
    "ee" : "whois.eenet.ee",
    "eg" : "whois.ripe.net",
    "es" : "whois.nic.es",
    "eu" : "whois.eu",
    "fi" : "whois.ficora.fi",
    "fo" : "whois.nic.fo",
    "fr" : "whois.nic.fr",
    "gd" : "whois.nic.gd",
    "gg" : "whois.gg",
    "gi" : "whois2.afilias-grs.net",
    "gl" : "whois.nic.gl",
    "gov" : "whois.nic.gov",
    "gs" : "whois.nic.gs",
    "gy" : "whois.registry.gy",
    "hk" : "whois.hkirc.hk",
    "hn" : "whois.nic.hn",
    "hr" : "whois.dns.hr",
    "ht" : "whois.nic.ht",
    "hu" : "whois.nic.hu",
    "ie" : "whois.domainregistry.ie",
    "il" : "whois.isoc.org.il",
    "im" : "whois.nic.im",
    "in" : "whois.inregistry.net",
    "info" : "whois.afilias.net",
    "int" : "whois.iana.org",
    "io" : "whois.nic.io",
    "iq" : "whois.cmc.iq",
    "ir" : "whois.nic.ir",
    "is" : "whois.isnic.is",
    "it" : "whois.nic.it",
    "je" : "whois.je",
    "jobs" : "jobswhois.verisign-grs.com",
    "jp" : "whois.jprs.jp",
    "ke" : "whois.kenic.or.ke",
    "kg" : "www.domain.kg",
    "ki" : "whois.nic.ki",
    "kr" : "whois.kr",
    "kz" : "whois.nic.kz",
    "la" : "whois.nic.la",
    "li" : "whois.nic.li",
    "lt" : "whois.domreg.lt",
    "lu" : "whois.dns.lu",
    "lv" : "whois.nic.lv",
    "ly" : "whois.nic.ly",
    "ma" : "whois.iam.net.ma",
    "md" : "whois.nic.md",
    "me" : "whois.nic.me",
    "mg" : "whois.nic.mg",
    "mil" : "whois.nic.mil",
    "ml" : "whois.dot.ml",
    "mn" : "whois.nic.mn",
    "mo" : "whois.monic.mo",
    "mobi" : "whois.dotmobiregistry.net",
    "mp" : "whois.nic.mp",
    "ms" : "whois.nic.ms",
    "mu" : "whois.nic.mu",
    "museum" : "whois.museum",
    "mx" : "whois.mx",
    "my" : "whois.domainregistry.my",
    "na" : "whois.na-nic.com.na",
    "name" : "whois.nic.name",
    "nc" : "whois.nc",
    "net" : "whois.verisign-grs.net",
    "nf" : "whois.nic.nf",
    "ng" : "whois.nic.net.ng",
    "nl" : "whois.domain-registry.nl",
    "no" : "whois.norid.no",
    "nu" : "whois.nic.nu",
    "nz" : "whois.srs.net.nz",
    "om" : "whois.registry.om",
    "org" : "whois.pir.org",
    "pe" : "kero.yachay.pe",
    "pf" : "whois.registry.pf",
    "pl" : "whois.dns.pl",
    "pm" : "whois.nic.pm",
    "post" : "whois.dotpostregistry.net",
    "pr" : "whois.nic.pr",
    "pro" : "whois.dotproregistry.net",
    "pt" : "whois.dns.pt",
    "pw" : "whois.nic.pw",
    "qa" : "whois.registry.qa",
    "re" : "whois.nic.re",
    "ro" : "whois.rotld.ro",
    "rs" : "whois.rnids.rs",
    "ru" : "whois.tcinet.ru",
    "sa" : "whois.nic.net.sa",
    "sb" : "whois.nic.net.sb",
    "sc" : "whois2.afilias-grs.net",
    "se" : "whois.iis.se",
    "sg" : "whois.sgnic.sg",
    "sh" : "whois.nic.sh",
    "si" : "whois.arnes.si",
    "sk" : "whois.sk-nic.sk",
    "sm" : "whois.nic.sm",
    "sn" : "whois.nic.sn",
    "so" : "whois.nic.so",
    "st" : "whois.nic.st",
    "su" : "whois.tcinet.ru",
    "sx" : "whois.sx",
    "sy" : "whois.tld.sy",
    "tc" : "whois.meridiantld.net",
    "tel" : "whois.nic.tel",
    "tf" : "whois.nic.tf",
    "th" : "whois.thnic.co.th",
    "tj" : "whois.nic.tj",
    "tk" : "whois.dot.tk",
    "tl" : "whois.nic.tl",
    "tm" : "whois.nic.tm",
    "tn" : "whois.ati.tn",
    "to" : "whois.tonic.to",
    "tp" : "whois.nic.tl",
    "tr" : "whois.nic.tr",
    "travel" : "whois.nic.travel",
    "tv" : "tvwhois.verisign-grs.com",
    "tw" : "whois.twnic.net.tw",
    "tz" : "whois.tznic.or.tz",
    "ua" : "whois.ua",
    "ug" : "whois.co.ug",
    "uk" : "whois.nic.uk",
    "us" : "whois.nic.us",
    "uy" : "whois.nic.org.uy",
    "uz" : "whois.cctld.uz",
    "vc" : "whois2.afilias-grs.net",
    "ve" : "whois.nic.ve",
    "vg" : "whois.adamsnames.tc",
    "wf" : "whois.nic.wf",
    "ws" : "whois.website.ws",
    "xxx" : "whois.nic.xxx",
    "yt" : "whois.nic.yt",
    "yu" : "whois.ripe.net"
}

WHOIS_PORT = 43

def whois_connect(domain, tld):
    root_domain = domain + '.' +  tld
    whois_server = WHOIS_SERVERS[tld]
    if not whois_server:
        print(f"Who is server for {root_domain} not found")
        return

    def _whois_send(host, payload):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as whois_tcp:
            whois_tcp.connect((host, WHOIS_PORT))
            whois_tcp.sendall(str.encode(f"{payload}\r\n"))
            return whois_tcp.recv(1024)

    return _whois_send(whois_server, root_domain)

if __name__ == '__main__':

    domain = "yahoo"
    tld = "com"
    whois_info = whois_connect(domain, tld)
    pprint(f""" ------------------ < WHOIS START >  ------------------
    ***** DATA RECEIVED:
    {whois_info}
    ------------------ < ***** >  ------------------
    """)
