import {boot}  from "../core.js";

export default function recipe(THREE) {
    const [renderer, camera, scene, clock] = boot(THREE, {
        cameraType: "perspective",
        fov: 45,
        aspect: window.innerWidth / window.innerHeight,
        near: 1,
        far: 500
    }, true);

    // Game components
    camera.position.set( 0, 0, 100 );
    camera.lookAt( 0, 0, 0 );

    // Creation of a LatheGeometry, A shape generated by spinning a line.
    // @docs https://threejs.org/manual/#en/primitives
    const points = [];
    for (let i = 0; i < 10; ++i) {
        points.push(new THREE.Vector2(Math.sin(i * 0.2) * 3 + 3, (i - 5) * .8));
    }
    const geometry = new THREE.LatheGeometry(points);
    const material = new THREE.MeshBasicMaterial( { color: 0xffff00 } );
    const lathe = new THREE.Mesh( geometry, material );
    scene.add( lathe );


    let t = 0;
    function animate(_t) {
        requestAnimationFrame( animate );


        renderer.render( scene, camera );
    }
    animate();
}




