worker_processes auto;

events {
    worker_connections 1024;
}


http {
    server {
        listen 80;
        server_name localhost;

        location / {
            root /data/www;
            try_files $uri $uri.html $uri/ =404; 
            # try_files makes http://localhost:8080/users work without .html extension
        }

        location /images/ {
            root /data;
        }
    }
}